### ISSUE TITLE
Could not find artifact jdk.tools:jdk.tools:jar:1.6 at specified path /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/../lib/tools.jar 

### ISSUE THREAD

**Issue by j143** [j143/systemds#153]
Error: [ERROR] Failed to execute goal on project systemds: Could not resolve dependencies for project org.apache.systemds:systemds:jar:2.1.0-SNAPSHOT: Could not find artifact jdk.tools:jdk.tools:jar:1.6 at specified path /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64/../lib/tools.jar -> [Help 1]

---
tools.jar has been removed from openjdk:

https://openjdk.java.net/jeps/220#:~:text=rt.jar%20and%20tools.jar

**Comment by j143** [comment]
The `jdk` is already the default

https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#installing-custom-java-package-type

```yml
steps:
- uses: actions/checkout@v2
- uses: actions/setup-java@v2
  with:
    distribution: '<distribution>'
    java-version: '11'
    java-package: jdk # optional (jdk or jre) - defaults to jdk
- run: java -cp java HelloWorldApp
```

**Comment by j143** [comment]
```yml
Java configuration:
  Distribution: adopt
  Version: 11.0.11+9
  Path: /opt/hostedtoolcache/Java_Adopt_jdk/11.0.11-9/x64
```
