### ISSUE TITLE
generated temp gpg key non interactively (unattended mode)

### ISSUE THREAD

**Issue by j143** [j143/systemds#154]
see https://www.gnupg.org/documentation/manuals/gnupg/Unattended-GPG-key-generation.html

```yml
- name: gpg key generation - transient
      run: >
        export GNUPGHOME="$(mktemp -d)"
        cat >tempkey <<EOF
          %echo Generating a basic OpenPGP key
          Key-Type: DSA
          Key-Length: 1024
          Subkey-Type: ELG-E
          Subkey-Length: 1024
          Name-Real: J143 Bot
          Name-Comment: with stupid passphrase
          Name-Email: j143+[bot]@protonmail.com
          Expire-Date: 0
          Passphrase: asdfghjkl
          # Do a commit here, so that we can later print "done" :-)
          %commit
          %echo done
        EOF
        gpg --batch --generate-key tempkey
```
