### ISSUE TITLE
error: failed to solve: failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount676187870/sysds.Dockerfile: no such file or directory

### ISSUE THREAD

**Issue by j143** [j143/systemds#195]
Error: buildx call failed with: error: failed to solve: failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount676187870/sysds.Dockerfile: no such file or directory

**Comment by j143** [comment]
```yml
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/sysds.Dockerfile
        push: true
        tags: return01/test-ghactions-systemds:latest
```
