### ISSUE TITLE
Multiple keys in yaml/yml possible?

### ISSUE THREAD

**Issue by j143** [j143/systemds#212]
Usecase:

```yml
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - master
```

```diff
on:
+ push | pull_request:
-  push:
-    branches:
-      - master
-  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - master
```

References;
[1] https://yaml.org/spec/1.2.2/
[2] https://stackoverflow.com/a/4910818/7860306
