### ISSUE TITLE
Automatic command testing in the documentation

### ISSUE THREAD

**Issue by j143** [j143/systemds#34]
For example:

https://github.com/istio/istio.io/blob/master/README.md#testing-document-content
https://github.com/istio/istio/wiki/Istio-Test-Framework

Pay attention to page test!

![image](https://user-images.githubusercontent.com/53068787/100546850-7fbe0500-3289-11eb-8489-661d0f73b3cf.png)

Doc project ideas:

https://developers.google.com/season-of-docs/docs/project-ideas

**Comment by j143** [comment]
https://github.com/AlexanderPrendota/kotlin-samples-verifier/blob/master/action/examples-workflow/verify-samples-on-push.yml

```yml
        uses: vmishenev/kotlin-samples-pusher@master
        with:
          io-event: '' #unset io-event
          push-repository: 'https://github.com/vmishenev/kotlin-compiler-server'
          snippet-flags: 'kotlin'
          push-path: 'src/test/resources/test-compile-data/kotlin-web-site'
          username: '${{ secrets.GITHUB_TOKEN }}' #token with an access to create PR in push-repository and issue in this repository
          start-commit: '${{ github.event.before }}'
          end-commit: '${{ github.event.after }}'
```
